classes:
- system.linux.system.repo.docker
- system.kubernetes.pool.cluster
- system.salt.minion.cert.k8s_client
- system.salt.minion.cert.etcd_client
- cluster.{{ cookiecutter.cluster_name }}.infra
parameters:
  docker:
    host:
      pkgs:
        - docker-engine=1.12.6-0~ubuntu-xenial
        - python-docker
  kubernetes:
    pool:
      network:
        etcd:
          ssl:
            enabled: {{ cookiecutter.etcd_ssl }}
        image: {{ cookiecutter.calico_image }}
        calicoctl:
          image: {{ cookiecutter.calicoctl_image }}
        cni:
          image: {{ cookiecutter.calico_cni_image }}
    common:
      hyperkube:
        image: {{ cookiecutter.hyperkube_image }}
