classes:
- system.linux.system.repo.docker
- system.kubernetes.pool.cluster
- system.salt.minion.cert.k8s_client
- system.salt.minion.cert.etcd_client
- cluster.{{ cookiecutter.cluster_name }}.infra
parameters:
  _param:
    kubernetes_calicoctl_image: {{ cookiecutter.calicoctl_image }}
    kubernetes_calico_image: {{ cookiecutter.calico_image }}
    kubernetes_calico_cni_image: {{ cookiecutter.calico_cni_image }}
    kubernetes_hyperkube_image: {{ cookiecutter.hyperkube_image }}
  docker:
    host:
      pkgs:
        - docker-engine=1.12.6-0~ubuntu-xenial
        - python-docker
  kubernetes:
    pool:
      network:
        no_default_pools: {{ cookiecutter.calico_no_default_pools }}
        etcd:
          ssl:
            enabled: {{ cookiecutter.etcd_ssl }}
        image: ${_param:kubernetes_calico_image}
        calicoctl:
          image: ${_param:kubernetes_calicoctl_image}
        cni:
          image: ${_param:kubernetes_calico_cni_image}
        {%- if cookiecutter.stacklight_enabled == 'True' %}
        prometheus:
          enabled: true
        {%- endif %}
    common:
      hyperkube:
        image: ${_param:kubernetes_hyperkube_image}
