classes:
{%- if cookiecutter.get('local_repositories', 'False') == 'True' %}
- system.linux.system.repo_local.mcp.apt_mirantis.docker_legacy
- system.linux.system.repo_local.mcp.extra
- system.linux.system.repo_local.mcp.apt_mirantis.ubuntu
- system.linux.system.repo_local.mcp.apt_mirantis.saltstack_2016_3
{%- else %}
- system.linux.system.repo.docker_legacy
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.mcp.apt_mirantis.ubuntu
- system.linux.system.repo.mcp.apt_mirantis.saltstack_2016_3
{%- endif %}
- system.kubernetes.pool.cluster
- system.salt.minion.cert.k8s_client
- system.salt.minion.cert.etcd_client
{%- if cookiecutter.kubernetes_network_engine == 'opencontrail' %}
- cluster.{{ cookiecutter.cluster_name }}.opencontrail.compute
{%- endif %}
- cluster.{{ cookiecutter.cluster_name }}.infra
{%- if cookiecutter.use_default_network_scheme != 'False' %}
- cluster.{{ cookiecutter.cluster_name }}.kubernetes.networking.compute
{%- endif %}

parameters:
  {%- if cookiecutter.kubernetes_network_engine == 'calico' %}
  _param:
    kubernetes_calicoctl_image: {{ cookiecutter.calicoctl_image }}
    kubernetes_calico_image: {{ cookiecutter.calico_image }}
    kubernetes_calico_cni_image: {{ cookiecutter.calico_cni_image }}
    kubernetes_hyperkube_image: {{ cookiecutter.hyperkube_image }}
  {%- endif %}
  docker:
    host:
      pkgs:
        - docker-engine=1.12.6-0~ubuntu-xenial
        - python-docker
  kubernetes:
    pool:
      network:
        no_default_pools: {{ cookiecutter.calico_no_default_pools }}
        etcd:
          ssl:
            enabled: {{ cookiecutter.etcd_ssl }}
        {%- if cookiecutter.kubernetes_network_engine == 'calico' %}
        image: ${_param:kubernetes_calico_image}
        calicoctl:
          image: ${_param:kubernetes_calicoctl_image}
        cni:
          image: ${_param:kubernetes_calico_cni_image}
        {%- elif cookiecutter.kubernetes_network_engine == 'opencontrail' %}}
        engine: opencontrail
        config:
          api:
            host: ${_param:opencontrail_control_address}
        {%- endif %}
        {%- if cookiecutter.stacklight_enabled == 'True' %}
        prometheus:
          enabled: true
        {%- endif %}
    common:
      hyperkube:
        image: ${_param:kubernetes_hyperkube_image}
  linux:
    system:
      package:
        docker-engine:
          version: 1.12.6-0~ubuntu-xenial
          hold: true
      kernel:
        sysctl:
          # The default operating system limits on mmap counts is likely to be too low, which may result in out of memory exceptions.
          vm.max_map_count: 262144
