classes:
  - service.libvirt.server.kvm
parameters:
  salt:
    control:
      enabled: True
      virt_enabled: True
      size:
        # TODO edit/add custom sizing as required
        ctl:
          cpu: 6
          ram: 12288
          disk_profile: default
          net_profile: default
        ntw:
          cpu: 4
          ram: 12288
          disk_profile: default
          net_profile: default
        nal:
          cpu: 4
          ram: 8192
          disk_profile: xlarge
          net_profile: default
        dbs:
          cpu: 4
          ram: 8192
          disk_profile: default
          net_profile: default
        prx:
          cpu: 4
          ram: 8192
          disk_profile: default
          net_profile: default
        mtr:
          cpu: 4
          ram: 8192
          disk_profile: medium
          net_profile: default
        mdb:
          cpu: 2
          ram: 8192
          disk_profile: default
          net_profile: default
        mon:
          cpu: 2
          ram: 8192
          disk_profile: default
          net_profile: default
        log:
          cpu: 4
          ram: 8192
          disk_profile: large
          net_profile: default
        bil:
          cpu: 2
          ram: 4096
          disk_profile: default
          net_profile: default
        jumpserver:
          cpu: 2
          ram: 8192
          disk_profile: medium
          net_profile: default

      cluster:
        internal:
          domain: {{cookiecutter.domain_name}}
          engine: virt
          node:
            # TODO edit/add placement nodes to provider hosts
            {%- for node_preffix in "bil ctl dbs log mdb mon mtr nal ntw prx".split() %}
              {%- for node in cookiecutter.keys()|sort %}
                {%- if node[5:] == '_ip' and node[:3] == node_preffix %}
            {{cookiecutter[node[:-3]+'_name']}}:
              provider: kvm{{node[3:5]}}.{{cookiecutter.domain_name}}
              image: "{{cookiecutter.apt_repository}}/images/ubuntu-14-04-x64-1458289056.qcow2"
              size: {{node_preffix}}
                {%- endif %}
              {%- endfor %}
            {%- endfor %}











