classes:
- service.etcd.server.cluster
- system.haproxy.proxy.listen.kubernetes.etcd
- system.linux.system.repo.docker
- system.salt.minion.pki.k8s_server_certificate
- system.kubernetes.master.cluster
- cluster.{{ cookiecutter.cluster_name }}.kubernetes.compute
- cluster.{{ cookiecutter.cluster_name }}
parameters:
  _param:
    keepalived_vip_interface: {{ cookiecutter.kubernetes_keepalived_vip_interface }}
    keepalived_vip_virtual_router_id: 60
  etcd:
    server:
      setup:
        calico:
          key: /calico/v1/ipam/v4/pool/${_param:calico_private_network}-${_param:calico_private_netmask}
          value: '{"masquerade": {{ cookiecutter.calico_enable_nat }}, "cidr": "${_param:calico_private_network}/${_param:calico_private_netmask}"}'