classes:
- system.linux.system.repo.docker
- system.kubernetes.pool.cluster
- system.salt.minion.cert.k8s_client
- system.salt.minion.cert.etcd_client
- cluster.{{ cookiecutter.cluster_name }}
parameters:
  kubernetes:
    pool:
      network:
        etcd:
          ssl:
            enabled: true
        image: {{ cookiecutter.calico_image }}
        calicoctl:
          image: {{ cookiecutter.calicoctl_image }}
        cni:
          image: {{ cookiecutter.calico_cni_image }}

    common:
      hyperkube:
        image: {{ cookiecutter.hyperkube_image }}
