classes:
{%- if cookiecutter.get('local_repositories', 'False') == 'True' %}
- system.linux.system.repo_local.mcp.extra
- system.linux.system.repo_local.mcp.apt_mirantis.openstack
- system.linux.system.repo_local.mcp.apt_mirantis.ubuntu
- system.linux.system.repo_local.mcp.apt_mirantis.saltstack
{%- if cookiecutter.stacklight_enabled == 'True' and cookiecutter.stacklight_version == '1' %}
- system.linux.system.repo_local.mcp.apt_mirantis.sensu
{%- endif %}
{%- else %}
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.mcp.apt_mirantis.openstack
- system.linux.system.repo.mcp.apt_mirantis.ubuntu
- system.linux.system.repo.mcp.apt_mirantis.saltstack
{%- if cookiecutter.stacklight_enabled == 'True' and cookiecutter.stacklight_version == '1' %}
- system.linux.system.repo.mcp.apt_mirantis.sensu
{%- endif %}
{%- endif %}
- system.galera.server.cluster
- system.galera.server.database.cinder
- system.galera.server.database.glance
{%- if cookiecutter.stacklight_enabled == 'True' %}
{%- if cookiecutter.openstack_version in ['mitaka', 'newton', 'ocata'] %}
- system.galera.server.database.aodh
- system.galera.server.database.ceilometer
{%- endif %}
- system.galera.server.database.grafana
{%- endif %}
- system.galera.server.database.heat
- system.galera.server.database.keystone
- system.galera.server.database.nova
- system.galera.server.database.neutron
#- haproxy.proxy.listen.openstack.galera.clustercheck
- cluster.{{ cookiecutter.cluster_name }}.infra
{%- if cookiecutter.use_default_network_scheme != 'False' %}
- cluster.{{ cookiecutter.cluster_name }}.openstack.networking.virtual
{%- endif %}
parameters:
  _param:
    keepalived_vip_interface: ens3
    keepalived_vip_virtual_router_id: 80
    galera_server_cluster_name: openstack_cluster
    cluster_vip_address: ${_param:openstack_database_address}
    cluster_local_address: ${_param:single_address}
    cluster_node01_hostname: ${_param:openstack_database_node01_hostname}
    cluster_node01_address: ${_param:openstack_database_node01_address}
    cluster_node02_hostname: ${_param:openstack_database_node02_hostname}
    cluster_node02_address: ${_param:openstack_database_node02_address}
    cluster_node03_hostname: ${_param:openstack_database_node03_hostname}
    cluster_node03_address: ${_param:openstack_database_node03_address}
