classes:
- system.backupninja.server.single
{%- if cookiecutter.openstack_enabled == 'True' %}
- system.xtrabackup.server.single
{%- endif %}
{%- if (cookiecutter.kubernetes_enabled == 'True' and cookiecutter.kubernetes_network_engine == 'opencontrail') or (cookiecutter.openstack_enabled == 'True' and cookiecutter.openstack_network_engine == 'opencontrail') %}
- system.cassandra.backup.server.single
- system.zookeeper.backup.server.single
{%- endif %}
{%- if cookiecutter.get('ceph_enabled', 'False') == 'True' %}
- system.ceph.backup.server.single
{%- endif %}
parameters:
  _param:
    backupninja_public_key: {{ cookiecutter.backup_public_key }}
{%- if cookiecutter.openstack_enabled == 'True' %}
    xtrabackup_public_key: {{ cookiecutter.backup_public_key }}
{%- endif %}
{%- if (cookiecutter.kubernetes_enabled == 'True' and cookiecutter.kubernetes_network_engine == 'opencontrail') or (cookiecutter.openstack_enabled == 'True' and cookiecutter.openstack_network_engine == 'opencontrail') %}
    zookeeper_backup_public_key: {{ cookiecutter.backup_public_key }}
    cassandra_backup_public_key: {{ cookiecutter.backup_public_key }}
{%- endif %}
{%- if cookiecutter.get('ceph_enabled', 'False') == 'True' %}
    ceph_backup_public_key: {{ cookiecutter.backup_public_key }}
{%- endif %}
