{%- macro password(size=16) -%}
{% for index in range(size) %}{{ 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'|random }}{% endfor %}
{%- endmacro %}
parameters:
  _param:
    salt_control_trusty_image: http://apt-mk.mirantis.com/images/ubuntu-14-04-x64-mcp1.0.qcow2
    salt_control_xenial_image: http://apt-mk.mirantis.com/images/ubuntu-16-04-x64-mcp1.0.qcow2
    
    # infra service addresses
    infra_config_hostname: {{ cookiecutter.salt_master_hostname }}
    infra_config_address: {{ cookiecutter.salt_master_address}}
    infra_config_deploy_address: {{ cookiecutter.salt_master_management_address }}

    infra_kvm_address: {{ cookiecutter.infra_kvm_vip_address }}
    infra_kvm_node01_address: {{ cookiecutter.infra_kvm01_control_address }}
    infra_kvm_node02_address: {{ cookiecutter.infra_kvm02_control_address }}
    infra_kvm_node03_address: {{ cookiecutter.infra_kvm03_control_address }}
    infra_kvm_node01_deploy_address: {{ cookiecutter.infra_kvm01_deploy_address }}
    infra_kvm_node02_deploy_address: {{ cookiecutter.infra_kvm02_deploy_address }}
    infra_kvm_node03_deploy_address: {{ cookiecutter.infra_kvm03_deploy_address }}
    infra_kvm_node01_hostname: {{ cookiecutter.infra_kvm01_hostname }}
    infra_kvm_node02_hostname: {{ cookiecutter.infra_kvm02_hostname }}
    infra_kvm_node03_hostname: {{ cookiecutter.infra_kvm03_hostname }}

    {%- if cookiecutter.storage_network_enabled == 'True' %}
    infra_compute_node01_storage_address: {{ cookiecutter.infra_kvm01_storage_address }}
    infra_compute_node02_storage_address: {{ cookiecutter.infra_kvm02_storage_address }}
    infra_compute_node03_storage_address: {{ cookiecutter.infra_kvm03_storage_address }}
    {%- endif %}

  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
        kvm01:
          address: ${_param:infra_compute_node01_address}
          names:
          - ${_param:infra_compute_node01_hostname}
          - ${_param:infra_compute_node01_hostname}.${_param:cluster_domain}
        kvm02:
          address: ${_param:infra_compute_node02_address}
          names:
          - ${_param:infra_compute_node02_hostname}
          - ${_param:infra_compute_node02_hostname}.${_param:cluster_domain}
        kvm03:
          address: ${_param:infra_compute_node03_address}
          names:
          - ${_param:infra_compute_node03_hostname}
          - ${_param:infra_compute_node03_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}