{%- if cookiecutter.deployment_type == 'physical' %}
classes:
{%- if cookiecutter.get('local_repositories', 'False') == 'True' %}
- system.linux.system.repo_local.mcp.apt_mirantis.maas
{%- else %}
- system.linux.system.repo.mcp.apt_mirantis.maas
{%- endif %}
- system.maas.region.single
- system.backupninja.client.single
- cluster.{{ cookiecutter.cluster_name }}.infra
parameters:
  _param:
    backupninja_backup_host: ${_param:infra_kvm_node03_address}
    backupninja_engine: rsync

  maas:
    region:
      commissioning_scripts:
        00-maas-05-simplify-network-interfaces: /etc/maas/files/commisioning_scripts/00-maas-05-simplify-network-interfaces
      bind:
        host: ${_param:deploy_address}
{%- if cookiecutter.upstream_proxy_enabled == 'True' %}
      upstream_proxy:
        address: {{ cookiecutter.upstream_proxy_address }}
        port: {{ cookiecutter.upstream_proxy_port }}
  {%- if cookiecutter.upstream_proxy_auth_enabled == 'True' %}
        user: {{ cookiecutter.upstream_proxy_user }}
        password: {{ cookiecutter.upstream_proxy_password }}
  {%- endif %}
{%- endif %}
{%- if cookiecutter.get('local_repositories', 'False') == 'True' %}
      maas_config:
        main_archive: http://${_param:local_repo_url}/ubuntu
{%- endif %}
    cluster:
      region:
        host: ${_param:deploy_address}
{%- if cookiecutter.get('local_repositories', 'False') == 'True' %}
      saltstack_repo_key: ${_param:aptly_gpg_public_key}
      saltstack_repo_trusty: "http://${_param:local_repo_url}/ubuntu-trusty ${_param:apt_mk_version} salt"
      saltstack_repo_xenial: "http://${_param:local_repo_url}/ubuntu-xenial ${_param:apt_mk_version} salt"
{%- endif %}
# linux:
#   network:
#     interface:
#       primary_interface:
#         enabled: true
#         name: ens2
#         type: eth
#         proto: static
#         netmask: ${_param:deploy_network_netmask}
#         address: ${_param:single_address}
#         gateway: ${_param:deploy_network_gateway}
#         name_servers:
#         - ${_param:dns_server01}
#         - ${_param:dns_server02}
### Sample MaaS Configuration
#  maas:
#    region:
#      subnets:
#        deploy_network:
#          cidr: 172.17.44.0/24
#          fabric: deploy_network
#          gateway_ip: 172.17.44.1
#          iprange:
#            end: 172.17.44.200
#            start: 172.17.44.92
#      fabrics:
#        deploy_network:
#          description: Fabric for deploy_network
#      machines:
{%- if cookiecutter.get('static_ips_on_deploy_network_enabled', 'False') == 'True' %}
#        kvm01:
#          interface:
#            mac: 00:25:90:e7:46:d0
#            subnet: deploy_network
#            mode: static
#            ip: ${_param:infra_kvm_node01_deploy_address}
#            gateway: ${_param:deploy_network_gateway}
#          power_parameters:
#            power_address: 176.74.220.208
#            power_password: vsHmCLc4z0aY
#            power_type: ipmi
#            power_user: engineer
#        kvm02:
#          interface:
#            mac: 00:25:90:e7:4b:52
#            subnet: deploy_network
#            mode: static
#            ip: ${_param:infra_kvm_node02_deploy_address}
#            gateway: ${_param:deploy_network_gateway}
#          power_parameters:
#            power_address: 176.74.220.214
#            power_password: vsHmCLc4z0aY
#            power_type: ipmi
#            power_user: engineer
#        kvm03:
#          interface:
#            mac: 00:25:90:e7:48:c6
#            subnet: deploy_network
#            mode: static
#            ip: ${_param:infra_kvm_node03_deploy_address}
#            gateway: ${_param:deploy_network_gateway}
#          power_parameters:
#            power_address: 176.74.220.216
#            power_password: vsHmCLc4z0aY
#            power_type: ipmi
#            power_user: engineer
  {%- if cookiecutter.openstack_network_engine == 'ovs' %}
#        gtw01:
#          interface:
#            mac: 00:25:90:e7:46:d0
#            subnet: deploy_network
#            mode: static
#            ip: ${_param:openstack_gateway_node01_deploy_address}
#            gateway: ${_param:deploy_network_gateway}
#          power_parameters:
#            power_address: 176.74.220.208
#            power_password: vsHmCLc4z0aY
#            power_type: ipmi
#            power_user: engineer
#        gtw02:
#          interface:
#            mac: 00:25:90:e7:4b:52
#            subnet: deploy_network
#            mode: static
#            ip: ${_param:openstack_gateway_node02_deploy_address}
#            gateway: ${_param:deploy_network_gateway}
#          power_parameters:
#            power_address: 176.74.220.214
#            power_password: vsHmCLc4z0aY
#            power_type: ipmi
#            power_user: engineer
#        gtw03:
#          interface:
#            mac: 00:25:90:e7:48:c6
#            subnet: deploy_network
#            mode: static
#            ip: ${_param:openstack_gateway_node03_deploy_address}
#            gateway: ${_param:deploy_network_gateway}
#          power_parameters:
#            power_address: 176.74.220.216
#            power_password: vsHmCLc4z0aY
#            power_type: ipmi
#            power_user: engineer
  {%- endif %}
    {%- for i in range(cookiecutter.openstack_compute_count|int) %}
    {%- set ip_start = 100 -%}
    {%- set cmp_start = 0 %}
#        cmp{{ "%03d"|format(cmp_start + loop.index) }}:
#          interface:
#            mac: 00:25:90:eb:92:4a
#            subnet: deploy_network
#            mode: static
#            ip: ${_param:openstack_compute_node{{ "%03d"|format(cmp_start + loop.index) }}_deploy_address}
#            gateway: ${_param:deploy_network_gateway}
#          power_parameters:
#            power_address: 185.8.58.225
#            power_password: vsHmCLc4z0aY
#            power_type: ipmi
#            power_user: engineer
    {%- endfor %}
  {%- if cookiecutter.get('ceph_enabled', 'False') == 'True' %}
    {%- if cookiecutter.get('ceph_hyper_converged', 'False') == 'False' %}
      {%- for i in range(cookiecutter.ceph_osd_node_count|int) %}
      {%- set ip_start = 200 -%}
      {%- set osd_start = 0 %}
#        osd{{ "%03d"|format(osd_start + loop.index) }}:
#          interface:
#            mac: 00:25:90:eb:92:4a
#            subnet: deploy_network
#            mode: static
#            ip: ${_param:ceph_osd_node{{ "%03d"|format(osd_start + loop.index) }}_deploy_address}
#            gateway: ${_param:deploy_network_gateway}
#          power_parameters:
#            power_address: 185.8.58.225
#            power_password: vsHmCLc4z0aY
#            power_type: ipmi
#            power_user: engineer
      {%- endfor %}
    {%- endif %}
  {%- endif %}
{%- else %}
#        kvm02:
#          interface:
#            mac: 00:25:90:eb:92:4a
#          power_parameters:
#            power_address: ipmi_ip
#            power_password: password
#            power_type: ipmi
#            power_user: engineer
{%- endif %}
{%- endif %}
