{%- if cookiecutter.deployment_type == 'physical' %}
classes:
{%- if cookiecutter.get('local_repositories', 'False') == 'True' %}
- system.linux.system.repo_local.maas
{%- else %}
- system.linux.system.repo.maas
{%- endif %}
- system.maas.region.single
- cluster.{{ cookiecutter.cluster_name }}.infra
parameters:
  maas:
    region:
      bind:
        host: ${_param:deploy_address}
{%- if cookiecutter.upstream_proxy_enabled == 'True' %}
      upstream_proxy:
        address: {{ cookiecutter.upstream_proxy_address }}
        port: {{ cookiecutter.upstream_proxy_port }}
{%- endif %}
{%- if cookiecutter.get('local_repositories', 'False') == 'True' %}
      maas_config:
        main_archive: http://${_param:local_repo_url}/ubuntu
{%- endif %}
    cluster:
      region:
        host: ${_param:deploy_address}
{%- if cookiecutter.get('local_repositories', 'False') == 'True' %}
      saltstack_repo_key: ${_param:aptly_gpg_public_key}
      saltstack_repo_trusty: "http://${_param:local_repo_url}/ubuntu-trusty stable salt"
      saltstack_repo_xenial: "http://${_param:local_repo_url}/ubuntu-xenial stable salt"
{%- endif %}
# linux:
#   network:
#     interface:
#       primary_interface:
#         enabled: true
#         name: ens2
#         type: eth
#         proto: static
#         netmask: ${_param:deploy_network_netmask}
#         address: ${_param:single_address}
#         gateway: ${_param:deploy_network_gateway}
#         name_servers:
#         - ${_param:dns_server01}
#         - ${_param:dns_server02}
### Sample MaaS Configuration
#  maas:
#    region:
#      subnets:
#        deploy_network:
#          cidr: 172.17.44.0/24
#          fabric: deploy_network
#          gateway_ip: 172.17.44.1
#          iprange:
#            end: 172.17.44.200
#            start: 172.17.44.92
#      fabrics:
#        deploy_network:
#          description: Fabric for deploy_network
#      machines:
#        kvm02:
#          interface:
#            mac: 00:25:90:eb:92:4a
#          power_parameters:
#            power_address: ipmi_ip
#            power_password: password
#            power_type: ipmi
#            power_user: engineer
{%- endif %}
