{%- macro password(size=16) -%}
{% for index in range(size) %}{{ 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'|random }}{% endfor %}
{%- endmacro %}
{%- macro secret(size=12) -%}
{% for index in range(size) %}{{ 'abcdef0123456789'|random }}{% endfor %}
{%- endmacro -%}
parameters:
  _param:
    # MAAS
    # Do not change below values as needed for prebuilt day01 image
    maas_admin_username: mirantis
    maas_admin_password: r00tme
    maas_db_password: fRqC7NJrBR0x

    {%- if cookiecutter.kubernetes_enabled == 'True' %}
    # K8S
    kubernetes_admin_password_generated: {{ password(16) }}
    kubernetes_admin_token_generated: {{ password(32) }}
    kubernetes_kubelet_token_generated: {{ password(32) }}
    kubernetes_kube-proxy_token_generated: {{ password(32) }}
    kubernetes_scheduler_token_generated: {{ password(32) }}
    kubernetes_controller-manager_token_generated: {{ password(32) }}
    kubernetes_dns_token_generated: {{ password(32) }}
    etcd_initial_token_generated: {{ password(32) }}
    {%- endif %}

    {%- if cookiecutter.stacklight_enabled == 'True' %}
    # StackLight
    grafana_password_generated: {{ password(16) }}
    mysql_grafana_password_generated: {{ password(16) }}
    influxdb_stacklight_password_generated: {{ password(16) }}
    influxdb_admin_password_generated: {{ password(16) }}
    influxdb_password_generated: {{ password(16) }}
    stacklight_log_keepalived_password_generated: {{ password(16) }}
    stacklight_telemetry_keepalived_password_generated: {{ password(16) }}
    keepalived_stacklight_monitor_vip_password_generated: {{ password(16) }}
    keepalived_prometheus_vip_password_generated: {{ password(16) }}
    stacklight_monitor_rabbitmq_password_generated: {{ password(16) }}
    stacklight_monitor_uchiwa_password_generated: {{ password(16) }}
    stacklight_monitor_keepalived_password_generated: {{ password(16) }}
    {%- endif %}

    {%- if cookiecutter.oss_enabled == 'True' %}
    # OSS
    oss_postgresql_admin_user_password_generated: {{ password(16) }}
    pushkin_db_user_password_generated: {{ password(16) }}
    secmonkey_db_user_password_generated: {{ password(16) }}
    docker_mongodb_admin_password_generated: {{ password(16) }}
    rundeck_db_user_password_generated: {{ password(16) }}
    oss_openstack_cert_generated: |
      {{ cookiecutter.oss_openstack_cert|indent(6) }}
    rundeck_runbook_public_key_generated: {{ cookiecutter.oss_runbook_public_key }}
    rundeck_runbook_private_key_generated: |
      {{ cookiecutter.oss_runbook_private_key|indent(6) }}
    {%- endif %}

    {%- if cookiecutter.openstack_enabled == 'True' %}
    # OpenStack
    horizon_secret_key_generated: {{ password(64) }}
    keystone_swift_password_generated: {{ password(16) }}
    rabbitmq_openstack_password_generated: {{ password(16) }}
    heat_domain_admin_password_generated: {{ password(16) }}
    ceilometer_influxdb_password_generated: {{ password(16) }}
    billometer_secret_key_generated: {{ password(64) }}
    mysql_aodh_password_generated: {{ password(16) }}
    mysql_cinder_password_generated: {{ password(16) }}
    mysql_ceilometer_password_generated: {{ password(16) }}
    mysql_glance_password_generated: {{ password(16) }}
    mysql_heat_password_generated: {{ password(16) }}
    mysql_keystone_password_generated: {{ password(16) }}
    mysql_neutron_password_generated: {{ password(16) }}
    mysql_nova_password_generated: {{ password(16) }}
    keystone_service_token_generated: {{ password(16) }}
    keystone_admin_password_generated: {{ password(16) }}
    keystone_ceilometer_password_generated: {{ password(16) }}
    keystone_cinder_password_generated: {{ password(16) }}
    keystone_glance_password_generated: {{ password(16) }}
    keystone_heat_password_generated: {{ password(16) }}
    keystone_keystone_password_generated: {{ password(16) }}
    keystone_neutron_password_generated: {{ password(16) }}
    keystone_nova_password_generated: {{ password(16) }}
    keystone_aodh_password_generated: {{ password(16) }}
    ceilometer_secret_key_generated: {{ password(16) }}
    mongodb_ceilometer_password_generated: {{ password(16) }}
    mongodb_admin_password_generated: {{ password(16) }}
    mongodb_shared_key_generated: {{ password(64) }}
    openstack_metadata_password_generated: {{ password(16) }}
    keystone_billometer_password_generated: {{ password(16) }}
    cinder_storage_secret_uuid_generated: "{{ secret(8) }}-{{ secret(4) }}-{{ secret(4) }}-{{ secret(4) }}-{{ secret(12) }}"
    nova_storage_secret_uuid_generated: "{{ secret(8) }}-{{ secret(4) }}-{{ secret(4) }}-{{ secret(4) }}-{{ secret(12) }}"
    {%- endif %}

    {%- if cookiecutter.opencontrail_enabled == 'True' %}
    # Opencontrail
    opencontrail_stats_password_generated: {{ password(16) }}
    {%- endif %}

    {%- if cookiecutter.cicd_enabled == 'True' %}
    # DriveTrain / CICD
    openldap_admin_password_generated: {{ password(16) }}
    openldap_config_password_generated: {{ password(16) }}
    openldap_readonly_password_generated: {{ password(16) }}
    jenkins_admin_password_generated: {{ password(16) }}
    gerrit_admin_password_generated: {{ password(16) }}
    cicd_keepalived_vip_password_generated: {{ password(16) }}
    cicd_mysql_admin_password_generated: {{ password(16) }}
    cicd_mysql_gerrit_password_generated: {{ password(16) }}
    jenkins_admin_public_key_generated: {{ cookiecutter.cicd_public_key }}
    jenkins_admin_private_key_generated: |
      {{ cookiecutter.cicd_private_key|indent(6) }}
    {%- endif %}

    {%- if cookiecutter.ceph_enabled == 'True' %}
    # Ceph
    rgw_keepalived_vip_password_generated: {{ password(11) }}
    ceph_cluster_fsid_generated: "{{ secret(8) }}-{{ secret(4) }}-{{ secret(4) }}-{{ secret(4) }}-{{ secret(12) }}"
    {%- endif %}

    {%- if cookiecutter.openstack_enabled == 'True' or cookiecutter.opencontrail_enabled == 'True' %}
    rabbitmq_admin_password_generated: {{ password(16) }}
    rabbitmq_secret_key_generated: {{ password(16) }}
    {%- endif %}

    {%- if cookiecutter.openstack_enabled == 'True' or cookiecutter.stacklight_enabled == 'True' %}
    galera_server_maintenance_password_generated: {{ password(16) }}
    galera_server_admin_password_generated: {{ password(16) }}
    {%- endif %}

    {%- if cookiecutter.cicd_enabled == 'True' or cookiecutter.stacklight_enabled == 'True' %}
    docker_registry_http_secret_generated: {{ password(16) }}
    {%- endif %}
    {%- if cookiecutter.get('vnf_onboarding_enabled', 'False') == 'True' and cookiecutter.get('vnf_onboarding_predeployed_resources', 'False') == 'True' %}
    vnf_openstack_admin_user_password_generated: {{ password(16) }}
    vnf_openstack_test_user_password_generated: {{ password(16) }}
    vnf_openstack_private_key_genereted: |
      {{ cookiecutter.vnf_openstack_private_key|indent(6) }}
    {%- endif %}
